spring:
  datasource:
    url: jdbc:postgresql://172.18.0.2:5432/postgres?currentSchema=public
    username: data_user
    password: 111
  jpa:
    show-sql: true

springdoc:
  show-oauth2-endpoints: true
  show-login-endpoint: true
server:
  port: 8082
logging:
  level:
    root: warn
    io:
      mbicycle: debug
default-admin:
  id: 1
frontend-url: "http://localhost:3000"