services:
  
  backend-server:
    image: backend-server
    ports:
      - '8082:8080'
    build:
      context: ./backend-server
      dockerfile: Dockerfile
    depends_on:
      - backend-server-db

  backend-server-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_USER=data_user'
      - 'POSTGRES_PASSWORD=111'