services:
  
  auth-server:
    image: auth-server
  
  resource-server:
    image: resource-server

  auth-server-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_USER=auth'
      - 'POSTGRES_PASSWORD=111'
    ports:
      - '5000:5432'

  resource-server-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_USER=resource'
      - 'POSTGRES_PASSWORD=111'
    ports:
      - '5001:5432'

  frontend:
    image: frontend