services:
  
  auth-server:
    image: auth-server
    ports:
      - '8081:8081'
    build:
      context: ./authorization-server
      dockerfile: Dockerfile
    depends_on:
      - auth-server-db
  
  resource-server:
    image: resource-server
    ports:
      - '8082:8080'
    build:
      context: ./resource-server
      dockerfile: Dockerfile
    depends_on:
      - auth-server
      - resource-server-db

  frontend:
    image: frontend
    ports:
      - '80:3000'
    build:
        context: ./frontend
        dockerfile: Dockerfile
    depends_on:
      - auth-server
      - resource-server

  auth-server-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_USER=auth_user'
      - 'POSTGRES_PASSWORD=111'

  resource-server-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_USER=resource_user'
      - 'POSTGRES_PASSWORD=111'