spring:
  datasource:
    url: jdbc:postgresql://resource-server-db:5432/postgres?currentSchema=public
    username: resource_user
    password: 111
  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
          jwk-set-uri: http://localhost:8081/oauth2/jwks

springdoc:
  show-oauth2-endpoints: true
  show-login-endpoint: true

logging:
  level:
    root: info
    org:
      springframework:
        security: debug
default-admin:
  id: 1