server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/postgres?currentSchema=auth
    username: auth_user
    password: 111
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework:
        security: debug
springdoc:
  show-oauth2-endpoints: true
