server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:postgresql://auth-server-db:5432/postgres?currentSchema=public
    username: auth_user
    password: 111
  data:
    redis:
      host: redis-revoke-token-storage
      port: 6379

logging:
  level:
    org:
      springframework:
        security: debug
springdoc:
  show-oauth2-endpoints: true
